# Generated by Django 4.1.5 on 2024-04-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctype_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('abbreviation', models.CharField(blank=True, max_length=150, null=True)),
                ('h_abbreviation', models.CharField(blank=True, max_length=150, null=True)),
                ('tm_abbreviation', models.CharField(blank=True, max_length=150, null=True)),
                ('tel_abbreviation', models.CharField(blank=True, max_length=150, null=True)),
                ('guj_abbreviation', models.CharField(blank=True, max_length=150, null=True)),
                ('ben_abbreviation', models.CharField(blank=True, max_length=150, null=True)),
                ('ctype', models.CharField(max_length=150)),
                ('createdate', models.DateTimeField(auto_now=True)),
                ('bActive', models.BooleanField(default=True)),
                ('showOnList', models.BooleanField(default=True)),
                ('fcategoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.ftype')),
            ],
        ),
    ]
