# Generated by Django 4.1.5 on 2024-04-11 09:42

from django.db import migrations, models
import django.db.models.deletion
import web_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0004_alter_ctype_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='broiler_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('h_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('tm_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('guj_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('ben_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.PositiveIntegerField()),
                ('createdate', models.DateTimeField(auto_now=True)),
                ('bActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='broiler_region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionid', models.IntegerField()),
                ('bfluctulate', models.IntegerField()),
                ('bnecc', models.IntegerField()),
                ('rateview', models.CharField(choices=[('N', 'N'), ('C', 'C')], default=web_admin.models.Status['N'], max_length=1)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('timeslot', models.CharField(blank=True, max_length=50, null=True)),
                ('bActive', models.BooleanField(default=True)),
                ('broilertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.broiler_type')),
                ('ctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.ctype_data')),
            ],
        ),
    ]
