# Generated by Django 4.1.5 on 2024-04-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0005_broiler_type_broiler_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broiler_type',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
