# Generated by Django 4.1.5 on 2024-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0007_broiler_region_broilertype_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broiler_region',
            name='rateview',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('C', 'C')], max_length=1, null=True),
        ),
    ]
