# Generated by Django 4.1.5 on 2024-04-11 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0008_alter_broiler_region_rateview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broiler_region',
            name='broilertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.broiler_type'),
        ),
    ]
