# Generated by Django 4.1.5 on 2024-04-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0009_alter_broiler_region_broilertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='state_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('h_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('tm_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('guj_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('ben_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('bActive', models.BooleanField(default=True)),
            ],
        ),
    ]
