# Generated by Django 4.1.5 on 2024-04-14 09:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0010_state_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctype_data',
            name='alias_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=50),
        ),
    ]
