# Generated by Django 4.1.5 on 2024-04-15 11:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0011_ctype_data_alias_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='broiler_region',
            name='alias_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=50),
        ),
        migrations.AddField(
            model_name='broiler_type',
            name='alias_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=50),
        ),
        migrations.AddField(
            model_name='ftype',
            name='alias_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=50),
        ),
        migrations.AddField(
            model_name='state_data',
            name='alias_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=50),
        ),
    ]
